### PR TITLE
/updates is about title/url changes (Item) and about changes (User)

### PR DESCRIPTION
**Pull request by localhostdotdev**
That's what I understand right now, but just starting out with the API so I might be wrong.

### CODE REVIEW

**Comment by sctb** [comment]
Hi!

There are more properties that can and do change for both items and profiles, so I think we'll leave this for now.

**Comment by localhostdotdev** [comment]
Thanks (actually I was kind of hoping to know which can change :) (as I can't open an issue :) ))

**Comment by sctb** [comment]
Ah! Here are the static fields—all others are subject to change:

Items:
* id
* type
* by
* time

Profiles:
* id
* created

**Comment by localhostdotdev** [comment]
Thanks, so those that can change:

- items: by, score
- stories (items): descendants, kids, title, url
- comments (items): kids, parent, text
- jobs (items): text, title, url
- polls (items): descendants, kids, parts, title
- pollopt (items): poll, text
- users (profiles): about, karma, submitted

Not sure about the `by` (maybe) and `parent` (unlikely, but possible) though, but I'm gonna stay by what you said unless I see otherwise.

**Pull request closed without merging**
