### PR TITLE
Update your API!

### PR DESCRIPTION
**Pull request by hzsweers**
You don't have issues enabled, so here's me trying to communicate that you guys never updated and newer SDKs can't consume your API

### CODE REVIEW

**Comment by sctb** [comment]
Thanks for pinging us, we're working on it with Firebase. You can always email us about the API at api@ycombinator.com

**Comment by hzsweers** [comment]
any update?

**Comment by sctb** [comment]
We’re still waiting on Firebase on the upgrade, since our account isn’t as straightforward as the average.

**Comment by hzsweers** [comment]
And now?

**Comment by sctb** [comment]
Still waiting on Google.

**Comment by hzsweers** [comment]
Waiting on what, exactly? If you don't mind me asking. Seems really strange that you'd be left hung out to dry for months when it was such a good bit of advertising for Firebase that you guys used them

**Comment by mikaturunen** [comment]
I agree with @hzsweers - no details, nothing and this is just starting sound more and more dubious. So what's actually going on?

**Comment by sctb** [comment]
I last spoke with Firebase support about a week ago and they said that the delay in migrating to the new platform is caused by some internal roadblocks because of the customization that was originally in place to support Hacker News. They seem very responsive, so at the moment I don't feel worried that we won't get it solved.

**Comment by sctb** [comment]
We've just upgraded the Hacker News API to the new console. Please let us know if there are any snags!

**Comment by AntouanK** [comment]
What does that mean exactly? Are there breaking changes?

**Comment by sctb** [comment]
There should not be any breaking changes to the documented REST API. It does mean two other things: 1) the API should continue working normally beyond the shutdown of the previous system (!) and 2) newer SDKs can now be used with the HN Firebase database.

**Pull request closed without merging**
